Update README.md
knightsamar/CS340_starter_flask_app pull request #1
Opened 2019-01-18 18:00 UTC by immaryw

update readme based on node.js instrution

2019-01-24 20:03 UTC, knightsamar requested changes
Thank you for your work on this Jing! Sorry for the late review. Could you please fix this before I merge it ?

2019-01-24 20:03 UTC, knightsamar commented on README.md
> +## Forever
Could you please rename this section to "Running the Flask application persistently" and add a link to:

1) http://flask.pocoo.org/docs/1.0/tutorial/deploy/#run-with-a-production-server
2) http://flask.pocoo.org/docs/1.0/deploying/wsgi-standalone/

2019-01-24 20:03 UTC, knightsamar commented on README.md
> +TBD - SKIPP THIS PART
We can copy paste this section from the NodeJS page if it exists.

2019-01-26 22:44 UTC, immaryw commented
They're updated. @knightsamar

2019-02-20 19:21 UTC, knightsamar approved these changes
Thanks a lot for your work on this, @immaryw!

2019-02-20 19:22 UTC, merged